### ISSUE TITLE
Scope variable is incorrect

### ISSUE THREAD

**Issue by Cortlandd** [jonhue/omniauth-paypal-oauth2#28]
**Describe the bug**
The scope defined at [line 8](https://github.com/jonhue/omniauth-paypal-oauth2/blob/master/lib/omniauth/strategies/paypal_oauth2.rb#L8) is incorrectly formatted. Paypal api requires is to contain `openid` and separated with spaces as specified [here](https://developer.paypal.com/docs/integration/direct/identity/attributes/).

**To Reproduce**
1. Go to 'YOURDOMAIN/users/auth/paypal_oauth2'
2. See error: Invalid scope

**Expected behavior**
Updating the scope [here](https://github.com/jonhue/omniauth-paypal-oauth2/blob/master/lib/omniauth/strategies/paypal_oauth2.rb#L8) to the following below will resolve the issue. And will be redirected to a paypal login

```ruby
DEFAULT_SCOPE = 'openid email profile'
```

**Desktop (please complete the following information):**
 - Any Browser

**Comment by jonhue** [comment]
Awesome! Would you be willing to submit a pull request?

**Comment by Cortlandd** [comment]
I can do that

**Comment by Cortlandd** [comment]
Submitted

**Comment by Cortlandd** [comment]
@jonhue is the fix included with version 1.4.15?

**Comment by jonhue** [comment]
No, for now fetch the gem from the master branch on GitHub.
