### ISSUE TITLE
Could not find matching strategy for "paypal_oauth2"

### ISSUE THREAD

**Issue by isen131** [jonhue/omniauth-paypal-oauth2#4]
Versions:

Ruby: 2.3.0p0
oauth2: 1.1.0
omniauth: 1.6.1
omniauth-oauth2: 1.4.0
omniauth-paypal-oauth2: 1.4.10

Logs:
```
/Users/evgeny/.rvm/gems/ruby-2.3.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:54:in `rescue in provider': Could not find matching strategy for "paypal_oauth2". You may need to install an additional gem (such as omniauth-paypal_oauth2). (LoadError)
	from /Users/evgeny/.rvm/gems/ruby-2.3.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:51:in `provider'
	from /Users/evgeny/Documents/Projects/houndandco/config/initializers/08_omniauth.rb:4:in `block in <top (required)>'
	from /Users/evgeny/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/evgeny/.rvm/gems/ruby-2.3.0/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
	from /Users/evgeny/.rvm/gems/ruby-2.3.0/gems/omniauth-1.6.1/lib/omniauth/builder.rb:6:in `initialize'
```

initializer:
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook, FACEBOOK_CONFIG['app_id'], FACEBOOK_CONFIG['app_secret'], :scope => 'email'
  provider :paypal_oauth2, PAYPAL_CONFIG['client_id'], PAYPAL_CONFIG['client_secret'], :strategy_class => OmniAuth::Strategies::PayPalOauth2
end
```

**Comment by jonhue** [comment]
I came across the same issue a while ago, and was able to circumvent it using [devise](https://github.com/jonhue/omniauth-paypal-oauth2#devise). I don't know why omniauth is complaining as the strategy is called [paypal_oauth2](https://github.com/jonhue/omniauth-paypal-oauth2/blob/master/lib/omniauth/strategies/paypal_oauth2.rb#L11). I need to take a deeper look at this behavior.

**Comment by dagi3d** [comment]
I had the same issue and found the origin the problem. The thing is that OmniAuth Builder uses this code to get the strategy class: `OmniAuth::Utils.camelize(klass.to_s)`(https://github.com/omniauth/omniauth/blob/master/lib/omniauth/builder.rb#L52) so that the name `paypal_oauth2` is converted in PaypalOAuth2 when the class is actually Pay**P**alOAuth2. 
Quick fix is to load the strategy by using the name `pay_pal_oauth2` instead.

**Comment by jonhue** [comment]
Thanks for the hint! Seems like, I did not pay enough attention to naming the class names appropriately :-)
I'll fix it.
