### ISSUE TITLE
Relax json version requirement

### ISSUE THREAD

**Issue by paulca** [jonhue/omniauth-paypal-oauth2#48]
Hi there,

In version 1.4.15, the dependency on `json` went from `~> 1.7` to `~> 2.1`.

I have a bunch of other omniauth strategies that also depend on `json` `~> 1.7`, so when I installed a later version of this gem, I couldn't bundle.

Does the dependency on `json` have to be strict? Is there divergence in the `json` API between `1.7` and `2.x`? Would it be possible to depend maybe on something like `'> 1.7', '< 3'`?

—P

**Comment by jonhue** [comment]
I'll fix this as soon as I get to it. If you have time I'd also be happy to review a pull request 🤗

**Comment by paulca** [comment]
(force-pushed an update after failing spec because I hadn't included the changed `Gemfile.lock`, but obviously it is required since there's a dependency change)

**Comment by paulca** [comment]
@jonhue PR happily provided. 🤝
