### ISSUE TITLE
invalid_request: redirect uri mismatch between auth code and token

### ISSUE THREAD

**Issue by sina-s** [jonhue/omniauth-paypal-oauth2#5]
First of all thanks for the great Gem.

I'm using
gem 'omniauth', '~> 1.6.1'
gem 'omniauth-oauth2', '~> 1.3.1'
gem 'omniauth-facebook', '~> 4.0.0'

During the callback phase, I get an "invalid_request: redirect URI mismatch between auth code and token" error. The issue seems to be introduced in omniauth-oauth2 1.4.0: https://github.com/intridea/omniauth-oauth2/issues/93
And the `callback_url` method redefinition proposed in the thread solves the issue.  
Since the beginning, this gem has been dependent on omniauth-oauth2 1.4.0. Wondering if there is a work around that it's working with 1.4.0 or can the dependency downgraded to omniauth-oauth2 1.3.1 or possibly defining callback_url in the strategy?

**Comment by sina-s** [comment]
I think whether passing params or not, or which ones to pass in the callback_url is very vendor specific matter. Overriding it per strategy makes the most sense to me. Opened a PR for it: https://github.com/jonhue/omniauth-paypal-oauth2/pull/6

**Comment by jonhue** [comment]
Thank you for helping out. I already made these changes locally, but has no time to test it. If it works well for you, we should merge it. :)

**Comment by jonhue** [comment]
I am going to push this to rubygems in the next 3-4 days.

**Comment by sina-s** [comment]
I have tested it, works fine. BTW, there is a better/more generic fix in omniauth-oauth2: https://github.com/intridea/omniauth-oauth2/pull/100 waiting to be merged. I believe that also fixes the issue and this can be reverted.
